### PR TITLE
answers-pap

### PR DESCRIPTION
**Pull request by LordSQKY**
Translated the answers to the language Papiamento

### CODE REVIEW

**Comment by mctrivia** [comment]
thank you for your time.  Will have to figure out how to add this as papiamento is not on the iso 639-1 standard.  Could you please rename to answers-pap.json which is the iso 639-2 standard and add in select box at line 15 of index.html

**Comment by LordSQKY** [comment]
Hey Matthew, can you clarify or be more specific with "add in select box at line 15 of index.html". I'm confused. I'll rename the the file.

**Comment by mctrivia** [comment]
<option value="pap">Papiamento</option>

Should be added as new line 15 so it is after English and before Swedish

**Comment by mctrivia** [comment]
just noticed format was in an older layout.  I already fixed to new layout but can you translate the last to lines of the new answers-pap.json

**Pull request merged**
